server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
    cluster:
      nodes: :${REDIS_NODES}
    password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "your-super-secret-key-that-is-very-long"
  access-token-expiration: 30000  # 30초
  refresh-token-expiration: 1800000  # 30분

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG